version: "3.8"
services:
  olm-docs:
    image: phummelen/openlittermap:latest
    container_name: ${ENVIRONMENT}-olm-docs
    restart: unless-stopped
    environment:
      - ENVIRONMENT
    ports:
      - "${WEB_PORT}:${WEB_PORT}"

networks:
  network:
    name: ${ENVIRONMENT}
