site_name: 'Documentation'
copyright: Copyright &copy; 2023 OpenLitterMap Community
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'                      # Where to put the English HTML files

theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/openlittermap-logo.png      # The logo is shared by all languages
  favicon: assets/images/favicon.ico              # The favicon is shared by all languages
  language: en                                    # The build's language
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand

extra_css:
  - assets/stylesheets/openlittermap.css            # CSS is shared by all languages

extra:                                              # Language Selection
  alternate:  
    - name: English
      link: /en/
      lang: en
    - name: Nederlands
      link: /nl/
      lang: nl
    - name: Français
      link: /fr/
      lang: fr
    - name: Deutsch
      link: /de/
      lang: de
  homepage: https://docs.openlittermap.com

plugins:
  - search:                                         
      lang: en                                      # Set language for search

nav:
- Welcome: index.md
- Main Steps: main-steps.md
- How to tag:
   - The basics: tagging-how-to.md
   - Via web: tagging-via-web.md
   - Via mobile: tagging-via-mobile.md
- FAQ: faq.md
- Contact us: contact.md
- On Youtube: youtube.md
- Littercoin: littercoin.md
- General Use:
  - Uploading Photos: uploading-photos.md
  - Categories: tags-categories.md
  - Tags: tags-tags.md
  - Verification Process: verification-process.md
- Development Use:
  - Common Info: dev/introduction.md
  - Version Control: dev/github.md
  - Container Management: dev/docker.md
  - Running Locally: dev/running-locally.md
- Releases: releases.md
