site_name: 'Documentatie'
copyright: Copyright &copy; 2023 OpenLitterMap Gemeenschap
docs_dir: '../../docs/nl'                           # Where to find the Dutch markdown files
site_dir: '../../generated/nl'                      # Where to put the Dutch HTML files

theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/openlittermap-logo.png      # The logo is shared by all languages
  favicon: assets/images/favicon.ico              # The favicon is shared by all languages
  language: nl                                    # The build's language
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    #- navigation.indexes
    #- navigation.sections
    #- navigation.tabs
    #- navigation.top
    #- navigation.instant
    #- navigation.tracking
  palette: 
    primary: black

extra_css:
  - assets/stylesheets/openlittermap.css            # CSS is shared by all languages

extra:
  alternate:                                        # Language Selection
    - name: English
      link: /en/
      lang: en
    - name: Nederlands
      link: /nl/
      lang: nl
    - name: Français
      link: /fr/
      lang: fr
    - name: Deutsch
      link: /de/
      lang: de
  homepage: https://docs.openlittermap.com

plugins:
  - search:                                         
      lang: nl                                      # Set language for search

nav:
- Welkom: index.md
- Van afval tot data, stap voor stap: first-steps.md
- Voorbeelden van gevonden zwerfafval en hoe te taggen: tagging-examples.md
- Tips en sneltoetsen: tips.md
- Evenementen waar je bij kunt helpen: events.md
- Interessante custom-tags: customtags.md
- Littercoin: littercoin.md
- Veel gestelde vragen: faq.md
- Wekelijkse meetup en notulen: meetup.md
- Succesverhalen: success-stories.md
- Melden van mogelijke fouten: issues.md
- Contact: contact.md
- Versies: releases.md





