site_name: 'Dokumentation'
docs_dir: '../../docs/de'                           # Where to find the German markdown files
site_dir: '../../generated/de'                      # Where to put the German HTML files

theme:
    name: material
    custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
    logo: assets/images/openlittermap-logo.png      # The logo is shared by all languages
    favicon: assets/images/favicon.ico              # The favicon is shared by all languages
    language: de                                    # The build's language

extra_css:
  - assets/stylesheets/openlittermap.css            # CSS is shared by all languages

extra:                                              # Language Selection
  alternate:  
    - name: English
      link: /en/
      lang: en
    - name: Nederlands
      link: /nl/
      lang: nl
    - name: Français
      link: /fr/
      lang: fr
    - name: Deutsch
      link: /de/
      lang: de

plugins:
  - search:                                         
      lang: en                                      # Set language for search

nav:
- Willkommen: index.md
