site_name: 'Documentation'
docs_dir: '../../docs/fr'                           # Where to find the French markdown files
site_dir: '../../generated/fr'                      # Where to put the French HTML files

theme:
    name: material
    custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
    logo: assets/images/openlittermap-logo.png      # The logo is shared by all languages
    favicon: assets/images/favicon.ico              # The favicon is shared by all languages
    language: fr                                    # The build's language

extra_css:
  - assets/stylesheets/openlittermap.css            # CSS is shared by all languages

extra:                                              # Language Selection
  alternate:  

      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Dutch
    - name: Nederlands
      link: /nl/
      lang: nl

    # Switch to French
    - name: Français
      link: /fr/
      lang: fr

plugins:
  - search:                                         
      lang: en                                      # Set language for search

nav:
- Bienvenue: index.md
